### ISSUE TITLE
Implement Canada Inc analytics

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/quran10#128]
```
Integrate app with Canada Inc analytics framework.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 23 Apr 2014 at 4:50

**Comment by canadainc** [comment]
c78e409d28a6f8203b835bc3d32d26ef43e1d058

**Comment by canadainc** [comment]
8d7c63f57b7af2c6f13bc4e010334a437cde063b

**Comment by canadainc** [comment]
8eb7764b4d6102ef3db8fa30ea3a5cb56efb14e8

**Comment by canadainc** [comment]
1ffe326cc18905c5c47d747cb65e2462e8779d47

**Comment by canadainc** [comment]
e1bc93240e33eefce0445f618dfb1d4c351e58fd

**Comment by canadainc** [comment]
936df7260043a1b6dcba6c13c37b884adca94340

**Comment by canadainc** [comment]
canadainclib: cfcd489d416188935a0bb7a6bf8b265ca7969e67
736fe376dee10d57c5fd3131160ea4b53fb45abc

**Comment by canadainc** [comment]
5973cbcb99fab1a10daf7e6cdb048d2675945dac

**Comment by canadainc** [comment]
002bc37a2963a8e833d576e580583e19dc76e5e2
