### ISSUE TITLE
Implement shortcut toast to return to previous pages

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/quran10#203]
```
To make it easy for users to jump around the app.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 23 Nov 2014 at 2:07

Attachments:
- [invoke.zip](https://storage.googleapis.com/google-code-attachments/quran10/issue-203/comment-0/invoke.zip)

**Comment by canadainc** [comment]
not worth dev effort.
