### ISSUE TITLE
Use an adaptive list for mushaf pages

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/quran10#204]
```
So user can relayout pages when orientation changes
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 23 Nov 2014 at 2:12

Attachments:
- [invoke.zip](https://storage.googleapis.com/google-code-attachments/quran10/issue-204/comment-0/invoke.zip)

**Comment by canadainc** [comment]
Not worth dev effort.
