### ISSUE TITLE
Replace Translation dropdown icons with flags

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/quran10#215]
```
Use flags instead
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 13 Jan 2015 at 8:03

**Comment by canadainc** [comment]
e32e8564675057cc0ce65d9dfee293169d1a223b

**Comment by canadainc** [comment]
Verified on 10.3.1.2744 on R135, GCR v4.3.0.0
