### ISSUE TITLE
Spanish localization

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/quran10#263]
```
https://github.com/quran/quran_android/tree/master/app/src/main/res/values-es
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 21 Feb 2015 at 2:40

**Comment by canadainc** [comment]
https://github.com/quran/quran_android/blob/master/app/src/main/res/values-es/sura_names.xml

**Comment by canadainc** [comment]
875dfae5c983cf7dee2bf6addfb29a36f845b1ca
