### ISSUE TITLE
Allow pinch gestures in the surah page to directly control the translation size

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/quran10#286]
```
The translation size should be controllable by simply doing a pinch gesture.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 11 Apr 2015 at 10:12

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744

Failed on:
R072 10.3.0.1424. From the AyatPage, you can't seem to zoom in or out.

**Comment by canadainc** [comment]
a9050f99ab8b99cf291b962f60394fb88b4f3ddb

**Comment by canadainc** [comment]
Verified on R072 10.3.0.1424
