### ISSUE TITLE
Arabic verse is getting cut off

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/quran10#287]
```
The ayat is getting cut off for user

Please see the attached screenshot
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 12 Apr 2015 at 2:28

Attachments:
* [IMG_20141028_163828.png](https://storage.googleapis.com/google-code-attachments/quran10/issue-287/comment-0/IMG_20141028_163828.png)

**Comment by canadainc** [comment]
Verified on 10.3.1.2744 on R135
Verified on 10.3.1.2744 on R081 (but the arabic text font changes to the native one)
Verified on 10.3.1.1779 on Lisbon  (but the arabic text font changes to the native one)
Verified on 10.3.2.557 on R144 (but the arabic text font changes to the native one)

**Comment by canadainc** [comment]
Verified on 10.3.0.1424 on R072
