### ISSUE TITLE
Maher bin Hamad Al-Mueaqly recitations don't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/quran10#297]
```
Seems like they were removed from the server.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 18 Apr 2015 at 11:38

**Comment by canadainc** [comment]
Downloads and plays correctly for both LQ & MQ.
Test using: Quran10 v4.0.0.4

Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
