### ISSUE TITLE
Unable to save multiple bookmarks.

### ISSUE THREAD

**Issue by anas17in** [canadainc/quran10#421]
Assalamualaikum. 
After upgrading to version 4.0 I am unable to save multiple bookmarks. The bookmarks menu is also not visible.
Sometimes it's very important to have multiple bookmarks.
Please provide multiple bookmark option like previous version.

**Comment by canadainc** [comment]
Wa'alaykum salam wa rahmatullahi wabarakathu.

This is still possible. They are just called 'Favourites' now. Simply tap on the ayat (instead of pressing and holding), and then in the ayat page, use the 'Mark Favourite' option.

See the video tutorial for more details.
