### ISSUE TITLE
translation issue

### ISSUE THREAD

**Issue by mohammedrasi** [canadainc/quran10#462]
check translation of 68:8

**Comment by canadainc** [comment]
As'salaamu'alaykum wa rahmatullah. What is wrong with the translation brother, please provide some details.

**Comment by mohammedrasi** [comment]
Wa alaikkum salaam wa rahmathullah..Sorry, it was my mistake. ‎Nothing wrong in that translation.                                                                                                                                      JazakAllahu ‎Khyran..                                                                                                                                                                                                   Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Canada IncSent: 2016, മേയ് 9, തിങ്കളാഴ്ച 04:01To: canadainc/quran10Reply To: canadainc/quran10Cc: mohammedrasi; AuthorSubject: Re: [canadainc/quran10] translation issue (#462)As'salaamu'alaykum wa rahmatullah. What is wrong with the translation brother, please provide some details.

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub
