### ISSUE TITLE
Performance and unit-testing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/quran10#60]
```
https://developer.blackberry.com/native/articles/analyze-performance-using-profi
ling/
```

Original issue reported on code.google.com by `genie...@gmail.com` on 15 Aug 2013 at 2:44

**Comment by canadainc** [comment]
6a07f8fc84df90ea5703f28807c52d93bb3f6efe

**Comment by canadainc** [comment]
283906ddd174dfcc5aca2d370c03eb4d468e4b36

**Comment by canadainc** [comment]
canadainc: 4aef9cb536f22dfbc31e880f66132932ef64b656

**Comment by canadainc** [comment]
0d46c18fd784c54dc0be2e9d4370a5398fb0baf0
