### ISSUE TITLE
Additional tafsir tracking

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/quran10#79]
```
Ticket to track additional tafsir.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 9 Dec 2013 at 11:26

Attachments:
- [IMG-20131021-WA000.jpg](https://storage.googleapis.com/google-code-attachments/quran10/issue-79/comment-0/IMG-20131021-WA000.jpg)
- [IMG-20131023-WA002.jpg](https://storage.googleapis.com/google-code-attachments/quran10/issue-79/comment-0/IMG-20131023-WA002.jpg)

**Comment by canadainc** [comment]
Verified with GCR v4.5.0.0
