### ISSUE TITLE
Implement widget mapper for database

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/quran10#88]
```
http://blackberry.github.io/Qt2Cascades-Samples/docs/sqlwidgetmapper.html
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 21 Feb 2014 at 3:42

Attachments:
- [sqlwidgetmapper.zip](https://storage.googleapis.com/google-code-attachments/quran10/issue-88/comment-0/sqlwidgetmapper.zip)

**Comment by canadainc** [comment]
not worth dev effort.
